# Generated by Django 4.0.5 on 2022-06-29 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Foot_catagorie',
            new_name='Catagori',
        ),
    ]
