# Generated by Django 4.0.5 on 2022-06-29 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foot', '0002_rename_foot_catagorie_catagori'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllFoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Yemek Adı')),
                ('price', models.PositiveIntegerField(verbose_name='Fiyatı')),
                ('foot_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foot.catagori', verbose_name='Yemek Tipi')),
                ('whos_foot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Restoran adı')),
            ],
        ),
    ]
