# Generated by Django 4.0.5 on 2022-06-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_sub_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Yemekler',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sub_type',
        ),
        migrations.AddField(
            model_name='user',
            name='sub',
            field=models.PositiveIntegerField(choices=[(1, 'Üye'), (2, 'Restoran Sahibi')], default=1),
        ),
    ]
